### ISSUE TITLE
Fixing TypeError: Function.prototype.apply: Arguments list has wrong type

### ISSUE THREAD

**Issue by t3knos** [Automattic/socket.io#1639]
This began to appear in v.1.0.4 and persists in v.1.0.5, and although it __appears__ that my socket.io-client is sending a string that looks like an object, I don't see how I've managed to do that.

```javascript
    /* Client code */
    var getAllRS_sock = io(svr,{
        'multiplex'                 : false,
        'timeout'                   : 5000,
        'transports'              : ['websocket'],
        'reconnection'                 : false,
        'sync disconnect on unload' : true,  // is this still available?        
    });
    /*** When connected, send get_AllRS ***/
    getAllRS_sock.on('connect', function getAllRS_sock_on_connect() {
        console.log('In getAllRS_sock_on_connect()');
        /*** Let's talk to the server ***/
        getAllRS_sock.emit('get_AllRS',{
                                'cType'     : 'get_AllRS',
                                'DEBUG'     : RS_DEBUG,
                                'clientID'  : clientID,
                                'userID'    : userID,
                            }) ;
    });

```

And the server looks like:

```javascript
    /* Server code */
    socket.sockets.on('connection', function socket_on_connection(clientSock){

        webClient = new WebClient(clientSock.id,clientSock.request.connection.remoteAddress,clientSock.request.connection.remotePort);
        logger.warn('+++> Client '+webClient.user+'@'+webClient.addy+':'+webClient.port+" ["+webClient.sess+'] connected ++++++++++++++');    

        clientSock.on('get_AllRS', function clientSock_on_get_AllRS(incomingData){
            logger.warn('*** INCOMING:',incomingData); // We never get this far.
        });
    });
```

Upon the client connecting to the server, the ```DEBUG``` shows the node server crash with the following:

```bash
[2014-06-19 12:13:49.112][8853][0@10.10.17.239:49673 [EaZQ5kULN0yMHRyMAAAA]][ctyp:undef][fnom:undef]
>> [WARN] [emitted] : +++> Client 0@10.10.17.239:49673 [EaZQ5kULN0yMHRyMAAAA] connected ++++++++++++++
[2014-06-19 12:13:49.113][8853][0@10.10.17.239:49673 [EaZQ5kULN0yMHRyMAAAA]][ctyp:undef][fnom:undef]
>> [ERROR] [console] :   socket.io:socket joined room EaZQ5kULN0yMHRyMAAAA +3ms
[2014-06-19 12:13:49.124][8853][0@10.10.17.239:49673 [EaZQ5kULN0yMHRyMAAAA]][ctyp:undef][fnom:undef]
>> [ERROR] [console] :   engine:ws received "42"[\"get_AllRS\", {\"cType\": \"get_AllRS\", \"DEBUG\": false, \"clientID\": \"2001\", \"userID\": \"190\"}]"" +13ms
[2014-06-19 12:13:49.125][8853][0@10.10.17.239:49673 [EaZQ5kULN0yMHRyMAAAA]][ctyp:undef][fnom:undef]
>> [ERROR] [console] :   engine:socket packet +15ms
[2014-06-19 12:13:49.125][8853][0@10.10.17.239:49673 [EaZQ5kULN0yMHRyMAAAA]][ctyp:undef][fnom:undef]
>> [ERROR] [console] :   socket.io-parser decoded 2"[\"get_AllRS\", {\"cType\": \"get_AllRS\", \"DEBUG\": false, \"clientID\": \"2001\", \"userID\": \"190\"}]" as {"type":2,"nsp":"/","data":"[\"get_AllRS\", {\"cType\": \"get_AllRS\", \"DEBUG\": false, \"clientID\": \"2001\", \"userID\": \"190\"}]"} +15ms
[2014-06-19 12:13:49.126][8853][0@10.10.17.239:49673 [EaZQ5kULN0yMHRyMAAAA]][ctyp:undef][fnom:undef]
>> [ERROR] [console] :   socket.io:socket got packet {"type":2,"nsp":"/","data":"[\"get_AllRS\", {\"cType\": \"get_AllRS\", \"DEBUG\": false, \"clientID\": \"2001\", \"userID\": \"190\"}]"} +14ms
[2014-06-19 12:13:49.126][8853][0@10.10.17.239:49673 [EaZQ5kULN0yMHRyMAAAA]][ctyp:undef][fnom:undef]
>> [ERROR] [console] :   socket.io:socket emitting event "[\"get_AllRS\", {\"cType\": \"get_AllRS\", \"DEBUG\": false, \"clientID\": \"2001\", \"userID\": \"190\"}]" +0ms

TypeError: Function.prototype.apply: Arguments list has wrong type
    at Socket.onevent (/usr/local/www/branches/00315/node/node_modules/socket.io/lib/socket.js:326:8)
    at Socket.onpacket (/usr/local/www/branches/00315/node/node_modules/socket.io/lib/socket.js:286:12)
    at Client.ondecoded (/usr/local/www/branches/00315/node/node_modules/socket.io/lib/client.js:181:14)
    at Decoder.Emitter.emit (/usr/local/www/branches/00315/node/node_modules/socket.io/node_modules/socket.io-parser/node_modules/emitter/index.js:132:20)
    at Decoder.add (/usr/local/www/branches/00315/node/node_modules/socket.io/node_modules/socket.io-parser/index.js:233:12)
    at Client.ondata (/usr/local/www/branches/00315/node/node_modules/socket.io/lib/client.js:166:16)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.onPacket (/usr/local/www/branches/00315/node/node_modules/socket.io/node_modules/engine.io/lib/socket.js:96:14)
    at WebSocket.EventEmitter.emit (events.js:95:17)
    at WebSocket.Transport.onPacket (/usr/local/www/branches/00315/node/node_modules/socket.io/node_modules/engine.io/lib/transport.js:91:8)
```

As you can see, the data from the client does appear to be a string:
```
engine:ws received "42"[\"get_AllRS\", {\"cType\": \"get_AllRS\", \"DEBUG\": false, \"clientID\": \"2001\", \"userID\": \"190\"}]""
```

So my hack of a solution was to check the type of data that came in, and convert it into an object if needed.  __This solves this problem.__

The following code appears in the ```node/node_modules/socket.io/lib/socket.js``` file, on around line 326.  I changed it

__FROM__
```javascript
/**
 * Called upon event packet.
 *
 * @param {Object} packet object
 * @api private
 */

Socket.prototype.onevent = function(packet){
  var args = packet.data || [];
  debug('emitting event %j', args);

  if (null != packet.id) {
    debug('attaching ack callback to event');
    args.push(this.ack(packet.id));
  }

  emit.apply(this, args);
};

```

__TO:__

```javascript
/**
 * Called upon event packet.
 *
 * @param {Object} packet object
 * @api private
 */

Socket.prototype.onevent = function(packet){
  var args = packet.data || [];
  debug('emitting event %j', args);

  if (typeof(args) === 'string'){
    debug('converted args to object')
    args = eval(args);
  }
  if (null != packet.id) {
    debug('attaching ack callback to event');
    args.push(this.ack(packet.id));
  }

  emit.apply(this, args);
};
```

Maybe this will help someone, and maybe someone could suggest a better solution?

Or maybe someone could point out to me how I managed to send a string instead of an object?

**Comment by rase-** [comment]
Closing due to inactivity.

Feel free to reopen if this is still an issue.

**Comment by ryoqun** [comment]
I'm not completely sure yet. But we may be affected by this issue too..
