### ISSUE TITLE
Listening to Port 80, Throws an Exception at Application Start-up

### ISSUE THREAD

**Issue by aireol** [Automattic/socket.io#1871]
An exception occurs:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at Object.<anonymous> (C:\inetpub\wwwroot\socketio_server\tst.js:5:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)`
```
when listening to port 80 (```server.listen(80);```), during application start up in `cmd`

Here's the source code:
```
var app = require('express')();
var server = require('http').Server(app);
var io = require('socket.io')(server);

server.listen(80);

io.on('connection', function(req, res){
    console.log('connection established');
});
```

**Comment by rase-** [comment]
This issue seems to be with the setup that you're using and will most likely happen when launching any HTTP server from node, not just socket.io.

I think StackOverflow would be a better place to ask for help with a Windoms + Node.js setup.
