### ISSUE TITLE
 (v1.2.1) Bug related checkRequest(req, fn) and origin

### ISSUE THREAD

**Issue by barneykim** [Automattic/socket.io#1919]
I'm testing node.js v0.10.33 and socket.io v1.2.1 with following code:
```javascript
var debug = require('debug')('simple'),
  server = require('http').createServer(),
  io = require('socket.io')(server, {
    origins: function (origin, fn) {
      if (origin == 'http://localhost:8080') {
        debug('allow origin [%s]', origin);
        return fn(null, true);
       }
       debug('disallow origin [%s]', origin);
        return fn(null, false);
      }
  });
server.listen(3000);
io.on('connection', function (socket) {
  debug('connection from client [%s]', socket.id);
  socket.on('disconnect', function () {
    debug('disconnect from clinet [%s]', this.id);
  });
});
```
Notice that the *origins* are defined.

**PROBLEM**
The node.js process died when I call by Fidder Web Debugger.
```
GET http://localhost:3000/socket.io/?EIO=3&transport=polling&t=1234567890-0 HTTP/1.1
Set-Cookie: io=1234567890
```
There is error messages:
```
/home/solv9kr/simple/node_modules/socket.io/lib/index.js:68
  if (this._origins.indexOf('*:*') !== -1) return fn(null, true);
                    ^
TypeError: Object function (origin, fn) {
                        if (origin == 'http://localhost:8080') {
                                debug('allow origin [%s]', origin);
                                return fn(null, true);
                        }
                        debug('disallow origin [%s]', origin);
                        return fn(null, false);
                } has no method 'indexOf'
    at Server.checkRequest (/home/solv9kr/simple/node_modules/socket.io/lib/index.js:68:21)
    at Server.verify (/home/solv9kr/simple/node_modules/socket.io/node_modules/engine.io/lib/server.js:127:17)
    at Server.handleRequest (/home/solv9kr/simple/node_modules/socket.io/node_modules/engine.io/lib/server.js:174:8)
    at Server.<anonymous> (/home/solv9kr/simple/node_modules/socket.io/node_modules/engine.io/lib/server.js:366:12)
    at Server.<anonymous> (/home/solv9kr/simple/node_modules/socket.io/lib/index.js:258:16)
    at Server.EventEmitter.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:525:27)
```

This problem is a bug related to socket.io/lib/index.js's *checkRequest(req, fn)* function.

```javascript
61 Server.prototype.checkRequest = function(req, fn) {
62  var origin = req.headers.origin || req.headers.referer;
63
64  // file:// URLs produce a null Origin which can't be authorized via echo-back
65  if ('null' == origin) origin = '*';
66
67  if (!!origin && typeof(this._origins) == 'function') return this._origins(origin, fn);
68  if (this._origins.indexOf('*:*') !== -1) return fn(null, true);
...
80  }
81  fn(null, false);
82 };
```
The socket.io was supposed to run 67 line because I was defining the origin function.
In this case 'origin' variable is **undefined**.
Then 65 line is passed and passed 67 line, and run 68 line.
The _origins variable is function. So TypeError is occurred and node.js is down.

**TO FIX**
I think that 65 line should change below to fix this bug.
```javascript
65   if ('null' == origin || !origin) origin = '*';
```

**Comment by defunctzombie** [comment]
Fixed via merging: https://github.com/drewblaisdell/socket.io/commit/a116d7765a6288eada3ece3574328e2e564a53d8
