### ISSUE TITLE
"TypeError: Cannot convert null to object" on socket disconnect

### ISSUE THREAD

**Issue by ROODAY** [Automattic/socket.io#1973]
Whenever a socket disconnects, I get the following error:

```
TypeError: Cannot convert null to object
    at Adapter.delAll (R:\Documents\GitHub\test\ChatAnon\node_modules\socket.io\node_modules\socket.io-adapter\index.js:80:31)
    at Socket.leaveAll (R:\Documents\GitHub\test\ChatAnon\node_modules\socket.io\lib\socket.js:258:16)
    at Socket.onclose (R:\Documents\GitHub\test\ChatAnon\node_modules\socket.io\lib\socket.js:393:8)
    at Client.onclose (R:\Documents\GitHub\test\ChatAnon\node_modules\socket.io\lib\client.js:208:12)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Socket.onClose (R:\Documents\GitHub\test\ChatAnon\node_modules\socket.io\node_modules\engine.io\lib\socket.js:243:10)
    at WebSocket.g (events.js:180:16)
    at WebSocket.EventEmitter.emit (events.js:92:17)
    at WebSocket.Transport.onClose (R:\Documents\GitHub\test\ChatAnon\node_modules\socket.io\node_modules\engine.io\lib\transport.js:113:8)
    at WebSocket.g (events.js:180:16)
```

This recently started to appear in a chat app I was making. It started around the same time that my form that I used to submit the messages from started to redirect the client to /? instead of just sending the message. Are these two issues related?

**Comment by ROODAY** [comment]
I fixed the form redirect issue, yet this issue still persists. Whenever a client disconnects, it throws the TypeError and crashes the whole application. Has anyone encountered this before?

**Comment by ROODAY** [comment]
It seems that my error was that I was misinterpreting how javascript's `=` is used. I thought I could make a copy of socket.io's roomlist and modify it as needed, but since it was a reference, I was messing with socket's internals. Here's the code that fixed it.

Original:
```
var roomList = io.sockets.adapter.rooms;
connectclients.forEach(function(client){
    delete roomList[client];
});
socket.emit("roomList", Object.keys(roomList));
```
Fixed:
```
var roomList = [];
Object.keys(io.sockets.adapter.rooms).forEach(function(room) {
    var isclient = false;
    connectclients.forEach(function(client){
        if (room === client) {
            isclient = true;
        }
    });
    if (isclient === false) {
        roomList.push(room);
    }
});
socket.emit("roomList", roomList);
```
