### ISSUE TITLE
How to force WebSocket transport?

### ISSUE THREAD

**Issue by ibc** [Automattic/socket.io#2002]
I do not see in the API how to force WebSocket transport. When I connect I see that it sends a GET request as follows:

```
https://DOMAIN/socket.io/?EIO=3&transport=polling&t=1423826616188-5252
```

and there is no "Upgrade: websocket" header.

**Comment by 3rd-Eden** [comment]
Why would you want to force websockets?

**Comment by ibc** [comment]
I've read about using `io.connect("http://your.domain.com", {transports: ['websocket']});` but such a `connect()` API does not exist (not in the API exposed in the README).

**Comment by ibc** [comment]
> Why would you want to force websockets?

I'm trying to make this library to work with an already running (and very old) version of socket.io server which I think just supports WebSocket. But not sure. The fact is that I receive a "connect_error" event when the above GET is sent:

```
"Error: server error
    at Socket.117.Socket.onPacket (http://test.local:3000/myBundle.js:38672:19)
    at XHR.<anonymous> (http://test.local:3000/myBundle.js:38496:10)
    at XHR.113.Emitter.emit (http://test.local:3000/myBundle.js:38060:20)
    at XHR.118.Transport.onPacket (http://test.local:3000/myBundle.js:39103:8)
    at 122.Polling.onData.callback (http://test.local:3000/myBundle.js:39943:10)
    at Object.129.exports.decodePayload (http://test.local:3000/myBundle.js:40900:12)
    at XHR.122.Polling.onData (http://test.local:3000/myBundle.js:39947:10)
    at Request.<anonymous> (http://test.local:3000/myBundle.js:39531:10)
    at Request.113.Emitter.emit (http://test.local:3000/myBundle.js:38060:20)
    at Request.121.Request.onData (http://test.local:3000/myBundle.js:39679:8)"
```

**Comment by 3rd-Eden** [comment]
Even if you were to able to force websockets, your idea would still not work because this latest version uses a different protocol encoding. So you wouldn't be able to connect

**Comment by ibc** [comment]
opps, nice to know! So thanks!
