### ISSUE TITLE
installation on win7x64 failes with iojs v1.5.1

### ISSUE THREAD

**Issue by fibric** [Automattic/socket.io#2057]
Hi,

I tried to install webpack-dev-server but it failed when socket.io is being compiled by VS.

```
C:\projects\javascript\products\ps.web\node_modules\webpack-dev-server\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2039: 'ExternalAsciiStringResource' : is not a member of 'v8::String' [C:\projects\javascript\products\ps.web\node_modules\webpack-dev-server\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
          C:\Users\denny.trebbin\.node-gyp\1.5.1\deps\v8\include\v8.h(1889) : see declaration of 'v8::String'
C:\projects\javascript\products\ps.web\node_modules\webpack-dev-server\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2065: 'ExternalAsciiStringResource' : undeclared identifier [C:\projects\javascript\products\ps.web\node_modules\webpack-dev-server\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
```

https://gist.github.com/fibric/13590b6b3a0dedae4d74

visual studio express 2012 is installed as well as python 2.7.9

**Comment by fibric** [comment]
As mentioned in Automattic/engine.io-client#376 its enough to update ws module.
That is what I did manually.

```
cd node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules
npm install ws@latest
```

and
```
cd node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client
npm install ws@latest
```

its dirty but it works for now.

**Comment by lygstate** [comment]
This should not be closed, socket.io-client doesn't compiled with iojs

**Comment by whampop** [comment]
Is this fixed?

**Comment by op1ekun** [comment]
Nope it's not...

`error C2039: 'ExternalAsciiStringResource': is not a member of 'v8::String'`

This happens on windows 10 and node 4.2.0

**Comment by lygstate** [comment]
It;s seems to be fixed, use a stable one.

**Comment by op1ekun** [comment]
Stable what?

I just forked another repository which has `socket.io-client` dependency:

```
...node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj(20,3): error MSB4019: The imported project "C:\Program
Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

and

```
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\bin\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\bin\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\dev\playground\gremlins\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
```

Doesn't look like fixed to me...

**Comment by nhhockeyplayer** [comment]
I have to bite my tongue when stumbling on these... its frustrating

the issue being, you cut pasted something into your package.json

for me it was one of these out of date
    "http-server": "^0.8.5",
    "jasmine": "2.3.2",
    "karma": "^0.12.23",
    "karma-chrome-launcher": "^0.1.4",
    "karma-cli": "^0.0.4",
    "karma-jasmine": "^0.3.6",
    "rimraf": "^2.4.3"

0. I zapped my node_modules dir
1. installed each one of these individually
2. then did npm install for the rest

it built fine

A developer can induce his own transient dependency via cut and paste... and these can be very aggravating aside from many other twists of the new way of doing things.

- cheers friend
