### ISSUE TITLE
Building failed with iojs 2.1.0 with vs 2013

### ISSUE THREAD

**Issue by lygstate** [Automattic/socket.io#2138]
```
$ npm install -g automattic/socket.io --msvs_version=2013
/


> utf-8-validate@1.1.0 install C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-
validate
> node-gyp rebuild


C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate>if not defined npm_con
fig_node_gyp (node "C:\Users\lygstate\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  e
lse (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  validation.cc
  win_delay_load_hook.c
     Creating library C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
  \build\Release\validation.lib and object C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_m
  odules\utf-8-validate\build\Release\validation.exp
  Generating code
  Finished generating code
  validation.vcxproj -> C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-valida
  te\build\Release\\validation.node
/


> bufferutil@1.1.0 install C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil

> node-gyp rebuild


C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil>if not defined npm_config_
node_gyp (node "C:\Users\lygstate\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else
rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
  win_delay_load_hook.c
     Creating library C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\bui
  ld\Release\bufferutil.lib and object C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modul
  es\bufferutil\build\Release\bufferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\b
  uild\Release\\bufferutil.node
\


> utf-8-validate@1.0.1 install C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-clien
t\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

|
C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\
utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\lygstate\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  validation.cc
c:\users\lygstate\appdata\roaming\npm\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules
\utf-8-validate\node_modules\nan\nan_implementation_12_inl.h(181): error C2660: 'v8::Signature::New' : function does not take 4 arguments [C:\Users\l
ygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-val
idate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\lygstate\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\lygstate\\AppData\\Roaming\\npm\\node.exe" "C:\\Users\\lygstate\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\
node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\
node_modules\utf-8-validate
gyp ERR! node -v v2.1.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

> bufferutil@1.0.1 install C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\no
de_modules\ws\node_modules\bufferutil
> node-gyp rebuild


C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\
bufferutil>if not defined npm_config_node_gyp (node "C:\Users\lygstate\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-
gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
c:\users\lygstate\appdata\roaming\npm\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules
\bufferutil\node_modules\nan\nan_implementation_12_inl.h(181): error C2660: 'v8::Signature::New' : function does not take 4 arguments [C:\Users\lygst
ate\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil\bu
ild\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\lygstate\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\lygstate\\AppData\\Roaming\\npm\\node.exe" "C:\\Users\\lygstate\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\
node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\
node_modules\bufferutil
gyp ERR! node -v v2.1.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.0.1
npm WARN optional dep failed, continuing bufferutil@1.0.1
socket.io@1.3.5 C:\Users\lygstate\AppData\Roaming\npm\node_modules\socket.io
├── has-binary@0.1.6 (isarray@0.0.1)
├── debug@2.1.3 (ms@0.7.0)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
├── socket.io-adapter@0.3.1 (debug@1.0.2, socket.io-parser@2.2.2)
├── engine.io@1.5.1 (base64id@0.1.0, engine.io-parser@1.2.1, accepts@1.1.4, ws@0.7.2)
└── socket.io-client@1.3.5 (indexof@0.0.1, to-array@0.1.3, component-emitter@1.2.0, component-bind@1.0.0, backo2@1.0.2, object-component@0.0.3, par
seuri@0.0.2, engine.io-client@1.5.1)

lygstate@lygstate-PC MINGW64 ~/AppData/Roaming/npm (master)
$
```

**Comment by lygstate** [comment]
From my inspect, this versions works:
#93b571406e3d8f950d9132d3f88bc55d055a6b13

**Comment by rauchg** [comment]
Fixed
